Repository Aridhia-Open-Source/PHEMS_federated_node, pull requests merged in 2024-11, with the labels that each got.

#55 release-pipeline-fix: Dynamic chart version based on the Chart.yaml
  .github/workflows/build.yml
  .github/workflows/create_release.yml
Labels: dev-ops

#58 ssl_term_fix: pre-install hook and default annotations on ns
  k8s/federated-node/Chart.yaml
  k8s/federated-node/templates/keycloak-namespace.yaml
  k8s/federated-node/templates/keycloak-realm-job.yaml
  k8s/federated-node/templates/keycloak-secret-initializer-job.yaml
  k8s/federated-node/templates/keycloak-start-configmap.yaml
  k8s/federated-node/templates/nginx-ingress.yaml
  k8s/federated-node/templates/nginx-namespace.yaml
Labels: dev-ops

#59 Reference for a standalone environment creation on Azure Cloud
  .github/workflows/build.yml
  environment/AZURE.md
Labels: documentation, dev-ops

#51 Edit dataset
  CHANGELOG.md
  k8s/federated-node/Chart.yaml
  webserver/app/datasets_api.py
  webserver/app/helpers/db.py
  webserver/app/helpers/keycloak.py
  webserver/app/helpers/wrappers.py
  webserver/app/models/catalogue.py
  webserver/app/models/dataset.py
  webserver/app/models/dictionary.py
  webserver/app/static/openapi.json
  webserver/docker-compose-tests-ci.yaml
  webserver/migrations/versions/3d3999b8de6a_field_name_in_dictionaries_non_nullable.py
  webserver/run_tests.sh
  webserver/tests/conftest.py
  webserver/tests/helpers/kubernetes.py
  webserver/tests/test_admin.py
  webserver/tests/test_catalogues.py
  webserver/tests/test_datasets.py
  webserver/tests/test_dictionaries.py
  webserver/tests/test_tasks.py
Labels: enhancement

#60 Tes output customizable
  CHANGELOG.md
  k8s/federated-node/templates/backend-registries-secret.yaml
  webserver/app/helpers/const.py
  webserver/app/helpers/kubernetes.py
  webserver/app/models/task.py
  webserver/app/static/openapi.json
  webserver/tests/conftest.py
  webserver/tests/files/results.tar.gz
  webserver/tests/test_datasets.py
  webserver/tests/test_kubernetes_helper.py
  webserver/tests/test_tasks.py
Labels: enhancement
